[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-url.herokuapp.com"

[context.development.environment]
  REACT_APP_API_URL = "http://localhost:8000"
