name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Replace with your test command, e.g., pytest
          pytest tests/

      - name: Build Docker image (if applicable)
        run: |
          docker build -t your-image-name .

      - name: Deploy to Production (optional)
        run: |
          # Add your deployment commands here, e.g., SSH to server
          echo "Deploying to production..."